CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[new_ssbcrmsystemssidwinner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbSSIDWinnerSourceSystem] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_seatgeekaccountid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_seatgeeksalesperson] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_seatgeekserviceperson] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_secondarymarket] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthclub] [bit] NULL,
[dal_ssb_sthreserve] [bit] NULL,
[dal_ssb_sthnonoption] [bit] NULL,
[dal_ssb_sthlegends] [bit] NULL,
[dal_ssb_sthowners] [bit] NULL,
[dal_ssb_sthfounders] [bit] NULL,
[dal_ssb_suiteregular] [bit] NULL,
[dal_ssb_suiteowners] [bit] NULL,
[dal_ssb_suitelegends] [bit] NULL,
[dal_ssb_stadiumclub] [bit] NULL,
[dal_ssb_cowboysclub] [bit] NULL,
[dal_ssb_cowboysfit] [bit] NULL,
[dal_ssb_secondarybuyer] [bit] NULL,
[dal_ssb_secondaryseller] [bit] NULL,
[dal_ssb_pglcowboys] [bit] NULL,
[dal_ssb_pglother] [bit] NULL,
[new_ssb_spend12months_cowboysevents] [decimal] (18, 6) NULL,
[new_ssb_spend12months_noncowboysevents] [decimal] (18, 6) NULL,
[new_ssb_spend12months_merch] [decimal] (18, 6) NULL,
[new_ssb_youthcamps] [decimal] (18, 6) NULL,
[new_ssb_fanclub] [decimal] (18, 6) NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbprimaryseatgeekid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_foundersprospect_cowboys] [bit] NULL,
[new_ssb_foundersprospect_collegefootball] [bit] NULL,
[parentcustomerid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_CONTACT_ID])
GO
